### ISSUE TITLE
Error when specifying E-flat in octave 4 or 5

### ISSUE THREAD

**Issue by mbedward** [leonawicz/tabr#1]
This works as expected:
```r
phrase("e_", info = "4")
```
But either of these results in an error:
```r
phrase("e_4", info = "4")
phrase("e_'", info = "4")
```
The message is `Error in mapply(substr, x, idx, idx + c(diff(idx), nchar(x) - utils::tail(idx,  : 
  zero-length inputs cannot be mixed with those of non-zero length`

Flattening any other note in octave 4 is fine.

Tested under:
tabr 0.1.0 
R 3.4.4
Windows 7

**Comment by leonawicz** [comment]
Thank you! I knew I was going to miss an E flat issue somewhere.

The default LilyPond language is Dutch, so sharps end in "is" and flats in "es". I chose to respect the default language for LilyPond, hence why `phrase` will make adjustments from `e_` to `ees` (and then `es`). It gets a little tricky with A and E, because LilyPond prefers those two pitches to have abbreviated notation: `as` and `es` rather than `aes` and `ees`. The docs say LilyPond accepts both... mostly. But I read that it is safer to use the two-letter version offered for those two notes because the three-letter version might not work in every part of LilyPond.

Anyway, this leads to a need for careful handling of splitting out pitches (the `mapply` call) where an `e` might not be part of a pitch but part of the flat suffix.

I'll get this fixed soon, this is top priority.

Matt

**Comment by leonawicz** [comment]
This should do it. I moved to abbreviated substitutions as late as possible in `phrase` while keeping substitution prior to any potentially attached text from `notate`. Here are some examples including a "chord" where I removed the spaces:

```
> eflats <- c("e_,, e_, e_ e_' e_''", "e_1 e_2 e_3 e_4 e_5")
> phrase(eflats[1], 4)
<es,,>4 <es,>4 <es>4 <es'>4 <es''>4
> phrase(eflats[2], 4)
<es,,>4 <es,>4 <es>4 <es'>4 <es''>4
> efchord <- gsub(" ", "", eflats)
> phrase(efchord[1], 4)
<es,, es, es es' es''>4
> phrase(efchord[2], 4)
<es,, es, es es' es''>4
```
I added more [unit tests](https://github.com/leonawicz/tabr/blob/master/tests/testthat/test-phrase.R) around `phrase`.

Thanks!

**Comment by mbedward** [comment]
Jeepers that was quick!  Thanks Matt.  It's working perfectly for me now.
