### ISSUE TITLE
Per-staff key signature

### ISSUE THREAD

**Issue by kimo-k** [leonawicz/tabr#14]
Hello,

Is there any support for different key signatures on each staff? I see that tracks can be transposed, but then their key signature seems limited to their transposition from the global key.

I could hack this to get what I want, but I'd rather not write phrases in arbitrary reverse transpositions.

Could `ms_key` be changed to support any key signature? Beyond compliance with shared staves, it seems doable to me.

**Comment by leonawicz** [comment]
I'm not sure it would be as easy as it sounds, but I'll have to dig into that part of the code to refresh. If memory serves, I implemented these args as they currently work for two reasons:

1. A use case I had where the tab is for the guitarist and it's played specifying a capo fret. The tab appears "as played" rather than "as sounds". But if sharing with someone playing another instrument, the music staff can be shown in the true key for their benefit.

2. I implemented it how it is now because (if I recall correctly) it turned out to be relatively easy to tell LilyPond to do a relative transposition of the staff on the fly. Or something along those lines.

At the moment I'm not sure what the possibilities are here or what level of effort is involved. On reading through again, I'm also not 100 percent certain I'm really understanding the request though so please let me know if I've got it wrong. I've been focused on other projects for awhile and `tabr` is a complex beast :)

**Comment by kimo-k** [comment]
Apologies for the delayed response. Let me try to clarify...

Your first reason is an important use case which I'm trying to make work. I tend to play in D standard, which is like a capo on the -2 fret, if that makes sense. 

The problem is that as soon as I apply `ms_transpose`, I can't seem to get all the tracks to render with the right key signature.

Suppose I'm playing a song in the actual key of B flat, which is C in my guitar fingering:

```
guitar   <- p('c d e f g a b c4','4')
vocal    <- p("b_ c' d' e_' f' g' a' b_'",'4')

t_guitar <- track(guitar, ms_transpose=-2,ms_key="b_")
t_vocal  <- track(vocal,music_staff='treble',no_tab=TRUE,ms_transpose=0)

trackbind(t_vocal,t_guitar) %>% score %>% tab("test3.pdf",key="b_")
```

Now my vocalist has the right notation, but my guitar is in four flats. Changing `ms_key` either has no effect, or puts my guitar in G# major (yikes). Changing `key` in `trackbind` to C puts my guitar in the appropriate key, but then my vocal track has the problem.

Maybe I'm missing something, but the interactions between `key`,`ms_transpose` and `ms_key` do not seem to make sense.

**Comment by leonawicz** [comment]
In prep for v0.4, a breaking but much needed change, there is no more `ms_transpose` or `ms_key`. The `track` function and affected code across several other functions has been completely refactored.

`track` now takes an explicit `key` argument. It defaults to `NA`, in which case it inherits from the global `key` set in the various sheet music rendering functions such as `tab` (global key is never `NA`). If provided to `track`, this key overrides the global key. Individual tracks can now have unique, explicit key signatures.

### Different key between music and tab staff

This is still supported. If you have a use case like I do where the tab staff is written with some implicit key (like relative to capo) while the music staff is in a different explicit key, but the way to do this has changed. It now requires two distinct tracks, one with music staff only, the other with the tab staff only. Prior to making otherwise duplicate phrases for each, transpose the notes as desired for the music staff track. [Second example](https://leonawicz.github.io/tabr/articles/tabr-tracks-scores.html#multiple-tracks) under Music Tracks section. It's not as "built in" as before, but this is all much more clearly expressed from start to finish.
