### ISSUE TITLE
notate() with rests not phrasey

### ISSUE THREAD

**Issue by kimo-k** [leonawicz/tabr#20]
```
> p('r', notate(1,'Pickup'))
Error: `x` is not phrasey.
> p('s', notate(1,'Pickup'))
Error: `x` is not phrasey.
```

**Comment by leonawicz** [comment]
Thanks. This will be fixed in the next update, though I won't be able to push it immediately. I'll close this once a fix is online.

Just a heads up, the next update on GitHub (preparing for v0.4.0) will bring a big overhaul to the package. There will be a lot more consistency throughout the package too. This 99% is in terms of music data analysis, also a lot of code optimization. Impact on transcription with LilyPond is close to none.

However, you may encounter some breaking changes where I intended to alter some function behavior or arguments. This can happen versions from time to time for versions less than 1.0 for packages, but really it's less than v0.5 means anything can happen. Again, I don't think you will be much affected by the changes, given what I know about your usage, but just so you know it's a big update. But all the documentation will be up to date along with it.

**Comment by leonawicz** [comment]
This should be fixed on GitHub now. Big update, other issues are sure to crop up.
