### ISSUE TITLE
 Invalid `key` with ms_transpose

### ISSUE THREAD

**Issue by kimo-k** [leonawicz/tabr#21]
```
> p('a','1') %>% track(ms_transpose=1) %>% score() %>% tab('test.pdf')
#### Engraving score to test.pdf ####
Error: Invalid `key`. See `keys()`.
```

**Comment by leonawicz** [comment]
This is related to a prior discussion of the current limitations of these arguments and underlying LilyPond templating. I'm going to keep this issue open until there is some progress on this more across the board. I'll make changes in stages because some of these will be lower hanging fruit than others.

If you transpose the music staff relative to the tab staff, you have to also provide `ms_key = "flat"` or `ms_key = "sharp"` (or a key that implies flats or sharps, though the key doesn't do anything extra). This is as sophisticated as it gets currently.

For example, if the global key of the entire score is `c` and you want a music staff that is transposed relative to the tab staff up one semitone, you set `ms_transpose = 1` but you also have to provide `ms_key` to clear up any ambiguity as to whether that means C# or Db. `ms_key` is needed for that, but does not do anything beyond that. This is also frustrating because you could say `ms_key = "d#m"` instead of `ms_key = "c#"` and the output will still correctly give you a music staff transposed to C#. This obviously needs to be improved. I will likely simplify this to one argument, and the user can either provide the relative semitone transposition or the absolute new key itself and either method will result in the new key for the music staff. I agree this is all very frustrating and at some point soon I will rework this. 

The underlying template also only offers the global key (which is set in `tab` or `lilypond`). I already feel like global arguments like that should actually be set in `score`, not in `tab`, because the score is, well, the score. And `tab`/`lilypond` just do the system communication and file writing. Makes sense to have `tab` parse those values as they were set in the score object rather than set them in the rendering call. So that's another pain point for me.

When I make the music staff key signature something you can set absolute rather than relative to the tab staff, that is a start in the right direction, but the issue that will still remain is that the tab staff itself is tied to the global key set later. That needs to be reworked separately. With the exception of transposing the music staves, overall the template really only permits one key per score.

Whatever I end up doing, they'll likely be the biggest breaking changes you'll see to the transcription side of `tabr`, but even so, they wouldn't be grave, and would open up more possibilities and clarity.

**Comment by kimo-k** [comment]
Thanks,
It's interesting how complex the problem is.
Clearly I need to spend some more time going through the documentation.
Maybe the error message should indicate or suggest this dependency on `ms_key`

**Comment by leonawicz** [comment]
See #14
