### ISSUE TITLE
Specifying strings in music strings

### ISSUE THREAD

**Issue by kimo-k** [leonawicz/tabr#23]
I'm learning to use music strings for transcription.
But I haven't yet found a good way specify string numbers when starting from a music string. 
I end up using something like `p(music_notes(x),music_info(x),strings)`.
Could you suggest a simpler way?

What would be really nice is if timesteps in music strings could have a delimiter for string number.

**Comment by leonawicz** [comment]
I'll give this some thought because I do think it will be valuable to enter string information seamlessly along with the way the `music` class interprets the other character input. It's the obvious next step. But it will be separate from `music`. The `music` class is brand new, sorry if the examples of how `phrase` can accept a music object as input made it seem like it was actually made with transcription in mind. Think of that more as I'm attempting to make `phrase` more general in what it can accept. But `music` is not intended to be a transcription-related class; just a class that aggregates the data in the other musical classes. I think I can find an elegant way to enter that data for `phrase` so it would be a lot like what you see input to `as_music` (plus string numbers), but without tainting the actual `music` class with instrument data. But to your immediate question, no, at the moment there is no way to enter all three things together for `phrase` like there is for `sf_phrase`. Hopefully soon. I'll leave this issue open and get back to you.

For context, basically to date, `phrase` (and its companion `sf_phrase`) has marked the firm divide between the small subset of transcription/lilypond-related package functions, and everything else- the broader music analysis package. And that gap is only going to get larger to the point that transcription would appear like an add-on suite. Since it's an R package, I know the potential user base is almost exclusively for the data analysis. Same for me. Both aspects are important to me though; I just plan to keep them clearly delineated to minimize confusion. So like in this case, I don't want to leak that stark instrument particularity or "how to play" context into the more pure music functions. That could frustrate a lot of potential users who see such functions, used near exclusively for data analysis, as too oddly slanted toward one application like guitar, or even transcription period. 

I'll find a good solution that offers what we're talking about while still keeping `phrase` as the kind of dividing line between general music analysis and veering down the transcription/lilypond path.

**Comment by leonawicz** [comment]
Okay this can be achieved now! :)

As I continued working on this and related things I found a nice way to allow optional inclusion of instrument string numbers when constructing a `music` class object from a new character string (wouldn't apply if coercing other objects to `music`, such as combining existing `noteworthy` and `noteinfo`). It is nice because it is seamless to do, but I downplay the option so that it does not detract from the more general musical purposes of the class.

You can now just add the starting string number after a semicolon. The only component that would still come after string numbers would be if you use the `*` operator. It will infer additional consecutive strings as needed. It will also be inherited by subsequent timesteps until an explicit change.

```
> x <- as_music("a,4;5 b, cgc'e' ce'~;51 ce'1")
> x
<Music string>
  Format: space-delimited time
  Values: a,4 b,4 <cgc'e'>4 <ce'~>4 <ce'>1

> summary(x)
<Music string>
  Timesteps: 5 (2 notes, 3 chords)
  Octaves: tick
  Accidentals: flat
  Key signature: c
  Time signature: 4/4
  Tempo: 2 = 60
  Lyrics: NA
  Strings: 5 5 5432 51 51
  Format: space-delimited time
  Values: a,4 b,4 <cgc'e'>4 <ce'~>4 <ce'>1

> phrase(x)
<Musical phrase>
<a,\5>4 <b,\5>4 <c\5 g\4 c'\3 e'\2>4 <c~\5 e'~\1>4 <c\5 e'\1>1
```

[Reference](https://leonawicz.github.io/tabr/reference/music.html)

On a related note, to be of more benefit to R users and users of R Markdown in particular, I decided it makes sense to make the clear line of where transcription begins a little fuzzier. But fuzzy in a clear way. 

`phrase` continues to mark where the more involved transcription pipeline begins. Building up from your input (e.g., a `music` object) to `phrase` to `track`, to `trackbind` if you have multiple voices or tracks, to `score` and finally to `tab` or `render_score` etc. If someone is doing something that complex with multiple voices or tracks, then they will continue operating in that post-`phrase` context.

However, I see a lot of value in "sheet music snippets". Shorter, simpler pieces of music like used in examples in a document. To that end, I've made an initial `render_music_*` family of functions that abstract away that whole pipeline above from the user. It is great for cases where you only have one voice, one track. You can use one of these wrapper functions, each with context-relevant default arguments based on its name, to make a sheet music or tablature snippet directly from a music object and skip the entire pipeline. These functions expose the relevant arguments directly and then go through that pipeline for you. Of course, it won't give as much control, but it's not supposed to. And while it is motivated by the snippets idea, there's no reason it has to be a short piece; just a structurally simpler one.

One other change overall is that now specifically when rendering to PNG, the default is to auto crop the whitespace of the output image, as opposed to PDF where it makes more sense to assume you want a full size paper page even if your content is much smaller. This is especially relevant for the `render_music_*` functions. (There's also a transparent background option for PNG now too.)

[Reference](https://leonawicz.github.io/tabr/reference/render_music.html)

**Comment by leonawicz** [comment]
Oh, and there is also better use of errors now for catching when string numbers in something like a music object are outside the range of strings as inferred from the `tuning` argument that applies to various rendering functions. So if your object has a string number `6` in it somewhere, but then you pass it to a function like `render_music_bass()` without changing the default 4-string `tuning`, it will properly catch that and throw an error now.
