### ISSUE TITLE
example code works on OS X!

### ISSUE THREAD

**Issue by brandly** [leonawicz/tabr#4]
i saw this in the README

> It has not yet been tested on Mac.

so i wanted to let you know [this example](https://github.com/leonawicz/tabr#r-code) worked great! i loaded things up in RStudio, and it spit out the `phrase.pdf` as expected.

also, i've been learning more R and have looked around for examples of well structured packages to learn from. you've got quite a few, so thanks for all the code!!

**Comment by leonawicz** [comment]
Thank you! My main concerns around not having Mac to test on were potential issues with accessibility of LilyPond by R. Since Mac is a lot like Linux, I was hopeful it similarly wouldn't have the kind of "cannot find" issues like you can get on Windows if you don't set the PATH. So the fact that you were able to run any example means the main concern is nothing to worry about.

Glad to hear the other packages are helpful :)
Matt
