### ISSUE TITLE
*Error: Explicit fret range will cut off notes.* when using "fret_range" parameter, function plot_fretboard

### ISSUE THREAD

**Issue by AHMcKenzie** [leonawicz/tabr#43]
Hello Matt,

Thanks for adding fret labels/numbers on the recent 0.5.0 update. I tried the new "fret_label" parameter but I'm getting this error message:

*Error: Explicit fret range will cut off notes.*

I'm using the "fret_range" clause on my scripts, they worked well before.  When used with your sample plot_fretboard() call, I get the same error message. This is the test line:

plot_fretboard (string, fret, "notes", show_tuning = TRUE, fret_labels = c(3, 5, 7, 9, 12), fret_range = c(4, 10))

I was able to circumvent the error by excluding a condition test you have in function plot_fretboard, around lines 148-151 in file "plot.R". This function has changed considerably so I don't know what other effects my change will introduce, but per your documentation "fret_range" should be able to constrain the fretboard range being rendered, and it is not.

Please advice, thanks,
Alex

**Comment by leonawicz** [comment]
Hi Alex,

The error is intentional. The prior behavior (still the default) was to infer from the `fret` argument the minimum fret range needed to contain all the `fret` values in the series.

I can likely improve the documentation to clarify, but the intended behavior when providing the new `fret_range` override is strictly to expand the range beyond that minimum. The `string` and `fret` series represent a sequence of musical information and `fret_range` is not intended for censoring the data and dropping notes out of a sequence so to speak. Whatever is passed to `string` and `fret` is meant to always be displayed in the image and not have anything cut off. The sequence is preserved. If `fret_range` would corrupt the given sequence, the explicit error is thrown.

`fret_label` is different. Since this is purely aesthetic in terms of which fret numbers to print on the image, it just uses the intersection of itself with the actual fret sequence displayed.

Regards,
Matt
